# Form implementation generated from reading ui file 'src\ui\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 320)
        MainWindow.setMinimumSize(QtCore.QSize(518, 320))
        MainWindow.setMaximumSize(QtCore.QSize(518, 320))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.button6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button6.sizePolicy().hasHeightForWidth())
        self.button6.setSizePolicy(sizePolicy)
        self.button6.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.button6.setText("")
        self.button6.setIconSize(QtCore.QSize(30, 30))
        self.button6.setAutoRepeat(False)
        self.button6.setDefault(False)
        self.button6.setFlat(False)
        self.button6.setObjectName("button6")
        self.gridLayout.addWidget(self.button6, 1, 2, 1, 1)
        self.button4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button4.sizePolicy().hasHeightForWidth())
        self.button4.setSizePolicy(sizePolicy)
        self.button4.setText("")
        self.button4.setIconSize(QtCore.QSize(30, 30))
        self.button4.setAutoRepeat(False)
        self.button4.setObjectName("button4")
        self.gridLayout.addWidget(self.button4, 1, 0, 1, 1)
        self.button5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button5.sizePolicy().hasHeightForWidth())
        self.button5.setSizePolicy(sizePolicy)
        self.button5.setSizeIncrement(QtCore.QSize(0, 0))
        self.button5.setWhatsThis("")
        self.button5.setText("")
        self.button5.setIconSize(QtCore.QSize(50, 50))
        self.button5.setCheckable(False)
        self.button5.setAutoDefault(True)
        self.button5.setDefault(True)
        self.button5.setFlat(False)
        self.button5.setObjectName("button5")
        self.gridLayout.addWidget(self.button5, 1, 1, 1, 1)
        self.button8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        self.button8.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button8.setText("")
        self.button8.setIconSize(QtCore.QSize(30, 30))
        self.button8.setAutoRepeat(False)
        self.button8.setFlat(False)
        self.button8.setObjectName("button8")
        self.gridLayout.addWidget(self.button8, 0, 1, 1, 1)
        self.button7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        self.button7.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button7.setText("")
        self.button7.setIconSize(QtCore.QSize(30, 30))
        self.button7.setAutoRepeat(False)
        self.button7.setFlat(False)
        self.button7.setObjectName("button7")
        self.gridLayout.addWidget(self.button7, 0, 0, 1, 1)
        self.button9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button9.sizePolicy().hasHeightForWidth())
        self.button9.setSizePolicy(sizePolicy)
        self.button9.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button9.setText("")
        self.button9.setIconSize(QtCore.QSize(30, 30))
        self.button9.setCheckable(False)
        self.button9.setChecked(False)
        self.button9.setAutoRepeat(False)
        self.button9.setDefault(False)
        self.button9.setFlat(False)
        self.button9.setObjectName("button9")
        self.gridLayout.addWidget(self.button9, 0, 2, 1, 1)
        self.button2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        self.button2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button2.setStatusTip("")
        self.button2.setText("")
        self.button2.setIconSize(QtCore.QSize(30, 30))
        self.button2.setAutoRepeat(False)
        self.button2.setFlat(False)
        self.button2.setObjectName("button2")
        self.gridLayout.addWidget(self.button2, 2, 1, 1, 1)
        self.button3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        self.button3.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button3.setText("")
        self.button3.setIconSize(QtCore.QSize(30, 30))
        self.button3.setAutoRepeat(False)
        self.button3.setFlat(False)
        self.button3.setObjectName("button3")
        self.gridLayout.addWidget(self.button3, 2, 2, 1, 1)
        self.button1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.button1.setText("")
        self.button1.setIconSize(QtCore.QSize(30, 30))
        self.button1.setAutoRepeat(False)
        self.button1.setDefault(False)
        self.button1.setFlat(False)
        self.button1.setObjectName("button1")
        self.gridLayout.addWidget(self.button1, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 2, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 518, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuNeu = QtWidgets.QMenu(parent=self.menuBar)
        self.menuNeu.setObjectName("menuNeu")
        self.menuDatei = QtWidgets.QMenu(parent=self.menuBar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menuBar)
        self.actionnew = QtGui.QAction(parent=MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionNeue_Aufgabe = QtGui.QAction(parent=MainWindow)
        self.actionNeue_Aufgabe.setObjectName("actionNeue_Aufgabe")
        self.action_ber_watnu = QtGui.QAction(parent=MainWindow)
        self.action_ber_watnu.setObjectName("action_ber_watnu")
        self.actionTutorial = QtGui.QAction(parent=MainWindow)
        self.actionTutorial.setObjectName("actionTutorial")
        self.actionSupport = QtGui.QAction(parent=MainWindow)
        self.actionSupport.setObjectName("actionSupport")
        self.actionNeues_Aufgabenfeld = QtGui.QAction(parent=MainWindow)
        self.actionNeues_Aufgabenfeld.setObjectName("actionNeues_Aufgabenfeld")
        self.actionFAQ = QtGui.QAction(parent=MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.actionAbout_Watnu = QtGui.QAction(parent=MainWindow)
        self.actionAbout_Watnu.setObjectName("actionAbout_Watnu")
        self.actionIssue_Tracker = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("src\\ui\\../extra/feathericons/github.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionIssue_Tracker.setIcon(icon)
        self.actionIssue_Tracker.setObjectName("actionIssue_Tracker")
        self.actionContact = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap("src\\ui\\../extra/feathericons/twitter.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionContact.setIcon(icon1)
        self.actionContact.setObjectName("actionContact")
        self.about = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap("src\\ui\\../extra/feathericons/aperture.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.about.setIcon(icon2)
        self.about.setObjectName("about")
        self.actionImport = QtGui.QAction(parent=MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtGui.QAction(parent=MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionSettings = QtGui.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionBeenden = QtGui.QAction(parent=MainWindow)
        self.actionBeenden.setShortcutVisibleInContextMenu(False)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionSupportMe = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap("src\\ui\\../extra/feathericons/gift.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionSupportMe.setIcon(icon3)
        self.actionSupportMe.setObjectName("actionSupportMe")
        self.attributions = QtGui.QAction(parent=MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap("src\\ui\\../extra/feathericons/feather.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.attributions.setIcon(icon4)
        self.attributions.setObjectName("attributions")
        self.actionReadme = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap("src\\ui\\../extra/feathericons/help-circle.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.actionReadme.setIcon(icon5)
        self.actionReadme.setObjectName("actionReadme")
        self.menuNeu.addAction(self.actionReadme)
        self.menuNeu.addAction(self.actionIssue_Tracker)
        self.menuNeu.addAction(self.actionContact)
        self.menuNeu.addAction(self.actionSupportMe)
        self.menuNeu.addAction(self.attributions)
        self.menuNeu.addAction(self.about)
        self.menuDatei.addAction(self.actionImport)
        self.menuDatei.addAction(self.actionExport)
        self.menuDatei.addAction(self.actionSettings)
        self.menuDatei.addSeparator()
        self.menuBar.addAction(self.menuDatei.menuAction())
        self.menuBar.addAction(self.menuNeu.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button5, self.button4)
        MainWindow.setTabOrder(self.button4, self.button1)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Watnu‽"))
        self.button6.setToolTip(_translate("MainWindow", "Neue Aufgabe"))
        self.button6.setShortcut(_translate("MainWindow", "6"))
        self.button4.setToolTip(_translate("MainWindow", "Aufgaben"))
        self.button4.setShortcut(_translate("MainWindow", "4"))
        self.button5.setToolTip(_translate("MainWindow", "Was kommt als nächstes?"))
        self.button5.setShortcut(_translate("MainWindow", "5"))
        self.button8.setToolTip(_translate("MainWindow", "Checkliste"))
        self.button8.setShortcut(_translate("MainWindow", "8"))
        self.button7.setToolTip(_translate("MainWindow", "TetraPlex"))
        self.button7.setShortcut(_translate("MainWindow", "7"))
        self.button9.setToolTip(_translate("MainWindow", "Missionen und Fähigkeiten"))
        self.button9.setShortcut(_translate("MainWindow", "9"))
        self.button2.setToolTip(_translate("MainWindow", "Inventar"))
        self.button2.setShortcut(_translate("MainWindow", "2"))
        self.button3.setToolTip(_translate("MainWindow", "Organisation"))
        self.button3.setShortcut(_translate("MainWindow", "3"))
        self.button1.setToolTip(_translate("MainWindow", "Statistik"))
        self.button1.setShortcut(_translate("MainWindow", "1"))
        self.menuNeu.setTitle(_translate("MainWindow", "Hilfe"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionExit.setText(_translate("MainWindow", "Schließen"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionNeue_Aufgabe.setText(_translate("MainWindow", "Neue Aufgabe"))
        self.action_ber_watnu.setText(_translate("MainWindow", "Über Watnu"))
        self.actionTutorial.setText(_translate("MainWindow", "Tutorial"))
        self.actionSupport.setText(_translate("MainWindow", "Kontakt"))
        self.actionNeues_Aufgabenfeld.setText(_translate("MainWindow", "Neuer Aufgabenbereich"))
        self.actionFAQ.setText(_translate("MainWindow", "FAQ"))
        self.actionAbout_Watnu.setText(_translate("MainWindow", "FAQ"))
        self.actionIssue_Tracker.setText(_translate("MainWindow", "Probleme/Anregungen melden..."))
        self.actionContact.setText(_translate("MainWindow", "Kontaktiere den Entwickler..."))
        self.about.setText(_translate("MainWindow", "Über Watnu"))
        self.actionImport.setText(_translate("MainWindow", "Importiere Aufgaben..."))
        self.actionExport.setText(_translate("MainWindow", "Exportiere Aufgaben..."))
        self.actionSettings.setText(_translate("MainWindow", "Einstellungen"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionBeenden.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSupportMe.setText(_translate("MainWindow", "Unterstütze den Entwickler..."))
        self.attributions.setText(_translate("MainWindow", "Thanks and Licenses"))
        self.actionReadme.setText(_translate("MainWindow", "FAQ und Wiki..."))
