# Form implementation generated from reading ui file 'src\ui\settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(660, 484)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_general)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.call_name_edit = QtWidgets.QPlainTextEdit(parent=self.tab_general)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.call_name_edit.sizePolicy().hasHeightForWidth())
        self.call_name_edit.setSizePolicy(sizePolicy)
        self.call_name_edit.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.call_name_edit.setObjectName("call_name_edit")
        self.formLayout_2.setWidget(
            1,
            QtWidgets.QFormLayout.ItemRole.FieldRole,
            self.call_name_edit,
        )
        self.label_5 = QtWidgets.QLabel(parent=self.tab_general)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_general, "")
        self.tab_categories = QtWidgets.QWidget()
        self.tab_categories.setObjectName("tab_categories")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_categories)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.categories_pages = QtWidgets.QTabWidget(parent=self.tab_categories)
        self.categories_pages.setObjectName("categories_pages")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.skills_table = QtWidgets.QTableWidget(parent=self.tab_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.skills_table.setFont(font)
        self.skills_table.setAutoFillBackground(True)
        self.skills_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.skills_table.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked
            | QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed
        )
        self.skills_table.setAlternatingRowColors(True)
        self.skills_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.skills_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.skills_table.setShowGrid(False)
        self.skills_table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.skills_table.setWordWrap(False)
        self.skills_table.setCornerButtonEnabled(False)
        self.skills_table.setColumnCount(3)
        self.skills_table.setObjectName("skills_table")
        self.skills_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.skills_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.skills_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.skills_table.setHorizontalHeaderItem(2, item)
        self.skills_table.horizontalHeader().setVisible(False)
        self.skills_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.skills_table)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            146,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.create_skill = QtWidgets.QPushButton(parent=self.tab_3)
        self.create_skill.setObjectName("create_skill")
        self.gridLayout_4.addWidget(self.create_skill, 0, 0, 1, 1)
        self.rename_skill = QtWidgets.QPushButton(parent=self.tab_3)
        self.rename_skill.setAutoDefault(True)
        self.rename_skill.setObjectName("rename_skill")
        self.gridLayout_4.addWidget(self.rename_skill, 0, 1, 1, 1)
        self.delete_skill = QtWidgets.QPushButton(parent=self.tab_3)
        self.delete_skill.setAutoDefault(True)
        self.delete_skill.setDefault(False)
        self.delete_skill.setObjectName("delete_skill")
        self.gridLayout_4.addWidget(self.delete_skill, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.categories_pages.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.categories_pages, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_categories, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_config)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.default_settings = QtWidgets.QGroupBox(parent=self.tab_config)
        self.default_settings.setObjectName("default_settings")
        self.horizontalLayout.addWidget(self.default_settings)
        self.user_settings = QtWidgets.QGroupBox(parent=self.tab_config)
        self.user_settings.setObjectName("user_settings")
        self.horizontalLayout.addWidget(self.user_settings)
        self.tabWidget.addTab(self.tab_config, "")
        self.tab_misc = QtWidgets.QWidget()
        self.tab_misc.setObjectName("tab_misc")
        self.clear_all_deleted = QtWidgets.QPushButton(parent=self.tab_misc)
        self.clear_all_deleted.setGeometry(QtCore.QRect(20, 10, 121, 21))
        self.clear_all_deleted.setObjectName("clear_all_deleted")
        self.clear_unused_resources = QtWidgets.QPushButton(parent=self.tab_misc)
        self.clear_unused_resources.setGeometry(QtCore.QRect(20, 40, 121, 21))
        self.clear_unused_resources.setObjectName("clear_unused_resources")
        self.tabWidget.addTab(self.tab_misc, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        self.categories_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Einstellungen"))
        self.call_name_edit.setPlaceholderText(_translate("Dialog", "Name"))
        self.label_5.setText(_translate("Dialog", "Wie du genannt werden möchtest"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_general),
            _translate("Dialog", "General"),
        )
        self.skills_table.setSortingEnabled(True)
        item = self.skills_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "activity_id"))
        item = self.skills_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name"))
        item = self.skills_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "#Aufgaben"))
        self.create_skill.setText(_translate("Dialog", "erstelle neu"))
        self.rename_skill.setText(_translate("Dialog", "benenne um"))
        self.delete_skill.setText(_translate("Dialog", "lösche"))
        self.categories_pages.setTabText(
            self.categories_pages.indexOf(self.tab_3),
            _translate("Dialog", "Skills"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_categories),
            _translate("Dialog", "Categories"),
        )
        self.default_settings.setTitle(_translate("Dialog", "default"))
        self.user_settings.setTitle(_translate("Dialog", "user-defined"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_config),
            _translate("Dialog", "Config"),
        )
        self.clear_all_deleted.setText(_translate("Dialog", "clear all deleted Tasks"))
        self.clear_unused_resources.setText(_translate("Dialog", "clear unused resources"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_misc),
            _translate("Dialog", "Misc"),
        )
