# Form implementation generated from reading ui file 'src\ui\tip_of_the_day.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(500, 348)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("C:/Users/micro/.designer/extra/watnu1.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        Wizard.setWindowIcon(icon)
        Wizard.setWizardStyle(QtWidgets.QWizard.WizardStyle.ModernStyle)
        Wizard.setOptions(
            QtWidgets.QWizard.WizardOption.HaveCustomButton1
            | QtWidgets.QWizard.WizardOption.HaveFinishButtonOnEarlyPages
            | QtWidgets.QWizard.WizardOption.HaveNextButtonOnLastPage
            | QtWidgets.QWizard.WizardOption.IndependentPages
            | QtWidgets.QWizard.WizardOption.NoCancelButton
            | QtWidgets.QWizard.WizardOption.NoCancelButtonOnLastPage
        )

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Did you know...?"))
