# Form implementation generated from reading ui file 'src\ui\tip_of_the_day.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tips(object):
    def setupUi(self, tips):
        tips.setObjectName("tips")
        tips.resize(500, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src\\ui\\../extra/watnu1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        tips.setWindowIcon(icon)
        tips.setWizardStyle(QtWidgets.QWizard.WizardStyle.ModernStyle)
        tips.setOptions(QtWidgets.QWizard.WizardOption.HaveCustomButton1|QtWidgets.QWizard.WizardOption.HaveNextButtonOnLastPage|QtWidgets.QWizard.WizardOption.IndependentPages|QtWidgets.QWizard.WizardOption.NoCancelButton|QtWidgets.QWizard.WizardOption.NoCancelButtonOnLastPage)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wizardPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tip_text = QtWidgets.QLabel(parent=self.wizardPage1)
        self.tip_text.setText("")
        self.tip_text.setObjectName("tip_text")
        self.verticalLayout.addWidget(self.tip_text)
        self.tip_visual = QtWidgets.QLabel(parent=self.wizardPage1)
        self.tip_visual.setText("")
        self.tip_visual.setScaledContents(True)
        self.tip_visual.setObjectName("tip_visual")
        self.verticalLayout.addWidget(self.tip_visual)
        tips.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        tips.addPage(self.wizardPage2)

        self.retranslateUi(tips)
        QtCore.QMetaObject.connectSlotsByName(tips)

    def retranslateUi(self, tips):
        _translate = QtCore.QCoreApplication.translate
        tips.setWindowTitle(_translate("tips", "Did you know...?"))
