# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(653, 278)
        self.activities_table = QtWidgets.QTableWidget(Dialog)
        self.activities_table.setGeometry(QtCore.QRect(10, 30, 594, 192))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.activities_table.setFont(font)
        self.activities_table.setAutoFillBackground(True)
        self.activities_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.activities_table.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.activities_table.setAlternatingRowColors(True)
        self.activities_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.activities_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.activities_table.setShowGrid(False)
        self.activities_table.setGridStyle(QtCore.Qt.SolidLine)
        self.activities_table.setWordWrap(False)
        self.activities_table.setCornerButtonEnabled(False)
        self.activities_table.setColumnCount(4)
        self.activities_table.setObjectName("activities_table")
        self.activities_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.activities_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activities_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activities_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.activities_table.setHorizontalHeaderItem(3, item)
        self.activities_table.horizontalHeader().setVisible(False)
        self.activities_table.verticalHeader().setVisible(False)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.activities_table.setSortingEnabled(True)
        item = self.activities_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "activity_id"))
        item = self.activities_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Name"))
        item = self.activities_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "∑ Zeit [min]"))
        item = self.activities_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "#Aufgaben"))
